# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(upload_to='img/news'),
        ),
    ]
