# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20171204_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgallery',
            name='path',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='new',
            name='new_type',
            field=models.IntegerField(choices=[(0, 'Text'), (1, 'Gallery'), (2, 'NoUrl')], default=0, verbose_name='Tipo'),
        ),
    ]
