# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20171204_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='newgallery',
            name='zip_import',
            field=models.FileField(blank=True, null=True, upload_to='img/news/zip', verbose_name='Zip import'),
        ),
    ]
