# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 02:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newgallery_zip_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='news.New')),
                ('image', models.ImageField(upload_to='img/carrousel')),
                ('poss', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Imagen del carrusel',
                'verbose_name_plural': 'Imagenes del carrusel',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='newgallery',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galerias'},
        ),
        migrations.RemoveField(
            model_name='newgallery',
            name='path',
        ),
        migrations.AlterOrderWithRespectTo(
            name='carousel',
            order_with_respect_to='poss',
        ),
    ]
